config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :email_templates
  root 'static#index'

  get 'static/index', as: 'home'

  get    'profile', to: 'users#show'
  get    'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'admin', to: 'admin_panel#index'
  get    'manage', to: 'bids#index'

  resources :users 
  resources :auctions do
    resources :items, only: [:index, :new, :create]
  end
  resources :items, only: [:show, :edit, :update, :destroy] do
    resources :bids, only: [:new, :create]
  end
  resources :bids, only: [:index, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  has_many :items

  validates :event_date, presence: true

  ATTR_NAMES = {:start_date => "Start date and time",
                :end_date   => "End date and time"}

  def event_date=(val)
    date = Date.strptime(val, "%m/%d/%Y") if val.present?
    write_attribute(:event_date, date)
  end

  def start_date=(val)
    date = DateTime.strptime(val, "%m/%d/%Y %l:%M %p") if val.present?
    write_attribute(:start_date, date)
  end

  def end_date=(val)
    date = DateTime.strptime(val, "%m/%d/%Y %l:%M %p") if val.present?
    write_attribute(:end_date, date)
  end

  def amount_raised=(val)
    currency = val.to_s.gsub(/[-$,]/,'').to_f if val.present?
    write_attribute(:amount_raised, currency)
  end

  def self.human_attribute_name(attr)
    ATTR_NAMES[attr.to_sym] || super
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)
    respond_to do |format|
      if @auction.save
        flash[:success] = 'Auction was successfully created.'
        format.html { redirect_to @auction }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        flash[:info] = 'Auction info was successfully updated.'
        format.html { redirect_to @auction }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      flash[:info] = 'Auction was successfully deleted.'
      format.html { redirect_to admin_panel_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    def authorize
      unless admin?
        flash[:danger] = 'You are not authorized to access this part of the site!'
        redirect_to(root_url) 
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.require(:auction).permit(:event_date, :start_date, :end_date, :active, :amount_raised)
    end

end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_listing.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Event Date</th>
      <th>Amounted Raised</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.order('event_date').reverse.each do |auction| %>
      <tr class="<%= auction.active ? 'success' : '' %>">
        <td><%= auction.event_date.to_formatted_s(:long) %></td>
        <td><%= number_to_currency(auction.amount_raised, :unit => "$") %></td>
        <td><div class="btn-group">
          <button class="btn btn-default btn-sm" title='Show Items' data-toggle="collapse" data-target=".items-list-<%= auction.id %>" >
            <span class="glyphicon glyphicon-list"></span>
          </button>
          <%= link_to auction_path(auction), class: "btn btn-default btn-sm", title: 'Show details' do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>
          <%= link_to edit_auction_path(auction), class: "btn btn-default btn-sm", title: 'Edit details' do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
          <%= link_to auction, method: :delete, data: { confirm: 'Are you sure you want to delete this auction?' }, class: "btn btn-default btn-sm", title: 'Delete auction' do %>
            <span class="glyphicon glyphicon-remove-sign"></span>
          <% end %>
        </div></td>
      </tr>
      <% if auction.items.present? %>
        <tr class="info collapse items_list items-list-<%= auction.id %>">
          <th>Item</th>
          <th><% if auction.active %>Current Bid<% else %>Winning Bid Amount<% end %></th>
          <th>Actions</th>
        </tr>
        <% auction.items.each do |item| %>
          <tr class="info collapse items-list-<%= auction.id %>">
            <td><%= item.item_title %></td>
            <td><% if !top_bid(item).nil? %><%= number_to_currency(top_bid(item).bid_amount, :unit => "$") %>
                <% else %> <%= number_to_currency(0, :unit => "$") %><% end %></td>
            <td><div class="btn-group">
              <%= link_to item_path(item), class: "btn btn-default btn-sm", title: 'Show details' do %>
                <span class="glyphicon glyphicon-search"></span>
              <% end %>
              <%= link_to edit_item_path(item), class: "btn btn-default btn-sm", title: 'Edit details' do %>
                <span class="glyphicon glyphicon-edit"></span>
              <% end %>
              <%= link_to item, method: :delete, data: { confirm: 'Are you sure you want to delete this item?' }, class: "btn btn-default btn-sm", title: 'Delete item' do %>
                <span class="glyphicon glyphicon-remove-sign"></span>
              <% end %>
            </div></td>
          </tr>
        <% end %>
      <% else %>
        <tr class="info collapse items_list items-list-<%= auction.id %>">
          <td colspan="3">This auction has no items.</td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/auctions/edit.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
	<h1>Editing Auction</h1>

	<%= simple_form_for(@auction) do |f| %>
	  <% if @auction.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

          <ul>
          <% @auction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
	  <div class="form-group">
	    <%= f.input :event_date, :as => :date_picker %>
	  </div>
	  <div class="form-group">
	    <%= f.input :start_date, :as => :datetime_picker,
	                input_html: {data: {date_options: {sideBySide: true}}} %>
	  </div>
	  <div class="form-group">
	    <%= f.input :end_date, :as => :datetime_picker,
	                input_html: {data: {date_options: {sideBySide: true}}} %>
	  </div>
	  <div class="form-group">
	    <%= f.label :amount_raised %>
	    <%= f.text_field :amount_raised, class: 'form-control', value: number_to_currency(@auction.amount_raised, unit: '$') %>
	  </div>
	  <div class="form-group">
		<%= f.label :active, class: 'checkbox inline' do %>
		    <%= f.check_box :active %>
		    <span>Make active auction</span>
		<% end %>
	  </div>
	  <div class="actions">
	    <%= f.submit "Update", class: "btn btn-primary" %>
	  </div>
	<% end %>

	<%= link_to 'Show', @auction %> |
	<%= link_to 'Back', admin_path %>

  </div>
</div>

app/views/auctions/index.html.erb
<h1>Listing Auctions</h1>

<%= render 'listing' %>

<%= link_to 'Back', admin_path %>

app/views/auctions/new.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
  	<h1>New Auction</h1>
	<%= simple_form_for(@auction) do |f| %>
	  <% if @auction.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

	      <ul>
	      <% @auction.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="form-group">
	    <%= f.input :event_date, :as => :date_picker, :class => 'form-control' %>
	  </div>
	  <div class="form-group">
	    <%= f.input :start_date, :as => :datetime_picker,
	                input_html: {data: {date_options: {sideBySide: true}}}, :class => 'form-control' %>
	  </div>
	  <div class="form-group">
	    <%= f.input :end_date, :as => :datetime_picker,
	                input_html: {data: {date_options: {sideBySide: true}}}, :class => 'form-control' %>
	  </div>
	  <div class="form-group">
	    <%= f.label :amount_raised %>
	    <%= f.text_field :amount_raised, class: 'form-control', value: number_to_currency(0.00, unit: '$') %>
	  </div>
	  <div class="form-group">
		<%= f.label :active, class: 'checkbox inline' do %>
		    <%= f.check_box :active %>
		    <span>Make active auction</span>
		<% end %>
	  </div>
	  <div class="actions">
	    <%= f.submit "Submit", class: "btn btn-primary" %>
	  </div>
	<% end %>
	<%= link_to 'Back', admin_path %>
  </div>
</div>

app/views/auctions/show.html.erb
<% if @auction.active %>
	<div class="alert alert-success">
		<strong>Active!</strong> This auction is currently active and items can be bid upon.
	</div>
<% else %>
	<div class="alert alert-danger">
		<strong>Inactive!</strong> This auction is inactive. Click update to make it active. Be sure to update the start and end dates and times.
	</div>
<% end %>
<div class="row">
  	<div class="col-sm-6 col-sm-offset-3">		
		<h1>Auction Details</h1>
		<p>
			<strong>Date of Auction</strong>
			<%= @auction.event_date.to_formatted_s(:long) %>
		</p>
		<p>
			<strong>Start Date and Time:</strong>
			<% if @auction.start_date.nil? %>
				None given. Update to set!
			<% else %> 
				<%= @auction.start_date.strftime("%A, %B %d, %Y %l:%M %p") %>
			<% end %>
		</p>
		<p>
			<strong>End Date and Time:</strong>
			<% if @auction.end_date.nil? %>
				None given. Update to set!
			<% else %>
				<%= @auction.end_date.strftime("%A, %B %d, %Y %l:%M %p") %>
			<% end %>
		</p>
		<p>
			<strong>Amount Raised:</strong>
			<%= number_to_currency(@auction.amount_raised, :unit => "$") %>
		</p>

		<div class="btn-group btn-group-justified">
			<%= link_to 'Update', edit_auction_path(@auction), class: 'btn btn-primary' %> 
			<%= link_to 'Back', admin_path, class: 'btn btn-primary' %>
		</div>
	</div>
</div>