config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :email_templates
  root 'static#index'

  get 'static/index', as: 'home'

  get    'profile', to: 'users#show'
  get    'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'admin', to: 'admin_panel#index'
  get    'manage', to: 'bids#index'

  resources :users 
  resources :auctions do
    resources :items, only: [:index, :new, :create]
  end
  resources :items, only: [:show, :edit, :update, :destroy] do
    resources :bids, only: [:new, :create]
  end
  resources :bids, only: [:index, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token, :reset_token

	before_save { self.email = email.downcase }
	validates :first_name,  presence: true, length: { maximum: 50 }
	validates :last_name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, 
		presence: true, 
		length: { maximum: 255 }, 
		format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitive: false }
	VALID_PHONE_NUMBER_REGEX = /\A[\d]{10}\z/
	validates :phone_number, format: { with: VALID_PHONE_NUMBER_REGEX }, allow_nil: true
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	# Returns random token for remembering login
	def User.new_token
    	SecureRandom.urlsafe_base64
  	end

  	# Returns the hash digest of the given string.
	def User.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
	end

	def create_reset_digest
		self.reset_token = User.new_token
		update_attribute(:reset_digest, User.digest(reset_token))
		update_attribute(:reset_sent_at, Time.zone.now)
	end

	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end

  	def remember
    	self.remember_token = User.new_token
    	update_attribute(:remember_digest, User.digest(remember_token))
  	end

  	def authenticated?(attribute, token)
  		digest = send("#{attribute}_digest")
  		return false if digest.nil?
    	BCrypt::Password.new(digest).is_password?(token)
  	end

    def forget
        update_attribute(:remember_digest, nil)
    end

    def password_reset_expired?
    	reset_sent_at < 2.hours.ago
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in, only: [:index, :show, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:index, :show, :edit, :update]
  before_action :authorize_user, only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    if !admin?
      flash[:danger] = 'You are not authorized to view this page!'
      redirect_to root_url
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        flash[:success] = 'Welcome to the And We\'re Walking Fundraising App! You are ready to start bidding!'
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:info] = 'Profile was successfully updated.'
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      flash[:info] = 'User was successfully deleted from the system.'
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def authorize_admin
      redirect_to(root_url) unless admin?
    end

    def authorize_user
      redirect_to(root_url) unless current_user.id==params[:id] || admin?
    end

    def logged_in
      unless logged_in?
        flash[:warning] = "Please log in!"
        redirect_to login_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation, :email, :notify_by_text, :notify_by_email, :name_visible, :phone_number)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>Edit User Preferences</h1>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :name_visible, class: 'checkbox inline' do %>
          <%= f.check_box :name_visible %>
          <span>Allow other users to see my name.</span>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :notify_by_email, class: 'checkbox inline' do %>
          <%= f.check_box :notify_by_email %>
          <span>Notify me by email when I'm outbid or win.</span>
        <% end %>
      </div>
      <!--<div class="form-group">
  	    <%= f.label :phone_number %>
  	    <%= f.text_field :phone_number, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :notify_by_text, class: 'checkbox inline' do %>
          <%= f.check_box :notify_by_text %>
          <span>Notify me by text when I'm outbid or win.</span>
        <% end %>
      </div> -->
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit "Update account", class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'Show', @user %> |
    <% if admin? %><%= link_to 'Back', users_path %><% else %><%= link_to 'Back', root_url %><% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.order('id').each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %> <%= user.last_name %></td>
        <td><div class="btn-group inline">
          <%= link_to user_path(user), class: "btn btn-default btn-sm", title: 'Show user' do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>
          <%= link_to edit_user_path(user), class: "btn btn-default btn-sm", title: 'Edit user' do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
          <%= link_to user, method: :delete, data: { confirm: 'Are you sure you want to delete this user?' }, class: "btn btn-default btn-sm", title: 'Delete user' do %>
            <span class="glyphicon glyphicon-remove-sign"></span>
          <% end %>
        </div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <% if !admin? %>
      <% provide(:title, 'Sign up') %>
      <h1>Sign Up</h1>
    <% else %>
      <h1>Create User</h1>
    <% end %>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <% if admin? %>
        <%= f.label :admin, class: 'checkbox inline' do %>
          <%= f.check_box :admin %>
          <span>Make admin</span>
        <% end %>
      <% end %>
      <div class="actions">
        <% if admin? %>
          <%= f.submit "Create new user", class: "btn btn-primary" %>
        <% else %>
          <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
      </div>
      <% if admin? %><%= link_to 'Back', users_path %><% else %><%= link_to 'Back', root_url %><% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>Account</h1>
    <p>
      <strong><%= @user.first_name %> <%= @user.last_name %></strong>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <!--<p>
      <strong>Phone number:</strong>
      <%= @user.phone_number %>
    </p>-->

    <p>
      <strong>Name visible to other users:</strong>
      <% if @user.name_visible %>Yes <% else %>No <% end %>
    </p>

    <p>
      <strong>Notify by email:</strong>
      <% if @user.notify_by_email %>Yes <% else %>No <% end %>
    </p>

<!--p>
      <strong>Notify by text:</strong>
      <% if @user.notify_by_text %>Yes <% else %>No <% end %>
    </p>-->

    <div class='btn-group btn-group-justified'>
    <%= link_to 'Update', edit_user_path(@user), class: 'btn btn-primary' %><% if admin? %><%= link_to 'Back', users_path, class: 'btn btn-primary' %><% else %><%= link_to 'Back', root_url, class: 'btn btn-primary' %><% end %>
  </div>
</div>