config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :email_templates
  root 'static#index'

  get 'static/index', as: 'home'

  get    'profile', to: 'users#show'
  get    'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'admin', to: 'admin_panel#index'
  get    'manage', to: 'bids#index'

  resources :users 
  resources :auctions do
    resources :items, only: [:index, :new, :create]
  end
  resources :items, only: [:show, :edit, :update, :destroy] do
    resources :bids, only: [:new, :create]
  end
  resources :bids, only: [:index, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <strong>Please fix the following <%= pluralize(@user.errors.count, "error") %> in the form.</strong>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-theme">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <%= link_to 'And We\'re Walking! Fundraising', root_url, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <% if admin? %>
          <li><%= link_to 'Admin', admin_path %></li>
        <% end %>
        <li class="dropdown">
          <a href='#' class="dropdown-toggle" data-toggle="dropdown" > Browse <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if Auction.where(active: true).count > 0 %>
              <% Auction.where(active: true).each do |auction| %>
                <li><%= link_to auction.event_date.to_formatted_s(:long) + ' Auction', auction_items_path(auction) %></li>
              <% end %>
            <% else %>
              There are currently no active auctions!<br>
              Thank you for your support!
            <% end %>
          </ul>
        </li>
        <% if logged_in? %>
          <li><%= link_to 'Manage Bids', manage_path %>
        	<li><%= link_to 'Account', user_path(@current_user) %></li>
        	<li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
	        <li><%= link_to 'Login', login_path %></li>
	        <li><%= link_to 'Sign Up', signup_path %></li>
	    <% end %>
      </ul>
    </div>
  </div>
</nav>