config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :email_templates
  root 'static#index'

  get 'static/index', as: 'home'

  get    'profile', to: 'users#show'
  get    'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'admin', to: 'admin_panel#index'
  get    'manage', to: 'bids#index'

  resources :users 
  resources :auctions do
    resources :items, only: [:index, :new, :create]
  end
  resources :items, only: [:show, :edit, :update, :destroy] do
    resources :bids, only: [:new, :create]
  end
  resources :bids, only: [:index, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :auction
  has_many :bids
  has_attached_file :image

  validates :item_title, presence: true;
  validates :item_value, presence: true;
  validates :starting_bid, presence: true;
  validates :min_increase, presence: true;
  validates_attachment :image, :content_type => { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    :size => { :in => 0..150.kilobytes }

  def item_value=(val)
    currency = val.to_s.gsub(/[-$,]/,'').to_f if val.present?
    write_attribute(:item_value, currency)
  end

  def starting_bid=(val)
    currency = val.to_s.gsub(/[-$,]/,'').to_f if val.present?
    write_attribute(:starting_bid, currency)
    write_attribute(:min_bid, currency)
  end

  def min_increase=(val)
    currency = val.to_s.gsub(/[-$,]/,'').to_f if val.present?
    write_attribute(:min_increase, currency)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in, only: [:edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:new, :create, :edit, :update, :destroy]


  # GET auctions/:auction_id/items
  def index
    auction = Auction.find(params[:auction_id])
    @items = auction.items
  end

  # GET /items/1
  def show
    @bids = @item.bids
  end

  # GET auctions/:auction_id/items/new
  def new
    auction = Auction.find(params[:auction_id])
    @item = auction.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST auctions/:auction_id/items
  # POST auctions/:auction_id/items.json
  def create
    auction = Auction.find(params[:auction_id])
    @item = auction.items.create(item_params)

    respond_to do |format|
      if @item.save
        flash[:success] = 'Item was successfully created.'
        format.html { redirect_to @item }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        flash[:success] = 'Item was successfully updated.'
        format.html { redirect_to @item }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      flash[:info] = 'Item was successfully deleted.'
      format.html { redirect_to admin_panel_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def logged_in
      unless logged_in?
        flash[:warning] = "Please log in!"
        redirect_to login_url
      end
    end

    def authorize
      unless admin?
        flash[:danger] = 'You are not authorized to access this part of the site!'
        redirect_to(root_url) 
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:item_title, :item_description, :item_value, :donor_name, :donor_visible, :starting_bid, :min_bid, :min_increase, :image)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
  def top_bid(item)
  	item.bids.order('bid_amount').reverse.first
  end
end

app/views/items/edit.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>Editing Item</h1>
    <%= form_for(@item, multipart: true) do |f| %>
      <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :item_title %>
        <%= f.text_field :item_title, class: 'form-control' %>
      </div>
      <div class="form-group">
      	<%= f.label :image %>
      	<%= f.file_field :image %>
      </div>
      <div class="form-group">
        <%= f.label :item_description %>
        <%= f.text_area :item_description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :item_value %>
        <%= f.text_field :item_value, class: 'form-control', value: number_to_currency(@item.item_value, unit: '$') %>
      </div>
      <div class="form-group">
        <%= f.label :starting_bid %>
        <%= f.text_field :starting_bid, class: 'form-control', value: number_to_currency(@item.starting_bid, unit: '$') %>
      </div>
      <div class="form-group">
        <%= f.label :min_increase %>
        <%= f.text_field :min_increase, class: 'form-control', value: number_to_currency(@item.min_increase, unit: '$') %>
      </div>
      <div class="form-group">
        <%= f.label :donor_name %>
        <%= f.text_field :donor_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :donor_visible, class: 'checkbox inline' do %>
          <%= f.check_box :donor_visible %>
          <span>Allow bidders to see who donated this item.</span>
        <% end %>
      </div>
      <div class="actions">
        <%= f.submit "Update Item", class: "btn btn-primary" %>
      </div>
    <% end %>
    <%= link_to 'Show', @item %> |
    <%= link_to 'Back', admin_path %>
  </div>
</div>

app/views/items/index.html.erb
<h1>Listing Items</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Item</th>
      <th>Value</th>
      <th>Highest Bid</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @items.order('id').each do |item| %>
      <tr>
        <td><%= item.item_title %></td>
        <td><%= number_to_currency(item.item_value, :unit => "$") %></td>
        <td><% if item.bids.present? %>
              <%= number_to_currency(top_bid(item).bid_amount, :unit => "$") %>
            <% else %>
              None
            <% end %></td>
        <td>
          <div class="btn-group">
            <% if logged_in? %><%= link_to new_item_bid_path(item), class: 'btn btn-success btn-sm' do %><span class="glyphicon glyphicon-usd"></span> Place Bid<% end %><% end %>
            <%= link_to item_path(item), class: "btn btn-default btn-sm", title: 'View item' do %>
              <span class="glyphicon glyphicon-search"></span> View Item
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin? %>
  <%= link_to 'Back', admin_path %>
<% else %>
  <%= link_to 'Home', root_url %>
<% end %>

app/views/items/new.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>New Item</h1>
    <%= form_for([@item.auction, @item], multipart: true) do |f| %>
      <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :item_title %>
        <%= f.text_field :item_title, class: 'form-control' %>
      </div>
      <div class="form-group">
      	<%= f.label :image %>
      	<%= f.file_field :image %>
      </div>
      <div class="form-group">
        <%= f.label :item_description %>
        <%= f.text_area :item_description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :item_value %>
        <%= f.text_field :item_value, class: 'form-control', value: '$' %>
      </div>
      <div class="form-group">
        <%= f.label :starting_bid %>
        <%= f.text_field :starting_bid, class: 'form-control', value: '$' %>
      </div>
      <div class="form-group">
        <%= f.label :min_increase %>
        <%= f.text_field :min_increase, class: 'form-control', value: '$' %>
      </div>
      <div class="form-group">
        <%= f.label :donor_name %>
        <%= f.text_field :donor_name, class: 'form-control' %>
      </div>
      <div class="form-group">
		    <%= f.label :donor_visible, class: 'checkbox inline' do %>
		    <%= f.check_box :donor_visible %>
		      <span>Allow bidders to see donor</span>
		    <% end %>
	    </div>
      <div class="actions">
        <%= f.submit "Create Item", class: "btn btn-primary" %>
      </div>
    <% end %>
    <%= link_to 'Back', admin_path %>
  </div>
</div>

app/views/items/show.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">		
	<h1>Item Details</h1>
	<p>
	  <% if !@item.image_file_name.nil? %>
	  	<%= image_tag @item.image.url, style: "float: right; margin: 0 10px;", class: "img-responsive" %>
	  <% end %>
	  <h4><%= @item.item_title %></h4>
	  <% if @item.donor_visible %>
	    <p>
	  	  <strong>Donor: </strong> <%= @item.donor_name %>
	  	</p>
	  <% end %>
	  <p>
	    <strong>Value: </strong> <%= number_to_currency(@item.item_value, :unit => "$") %>
	  </p>
	  <p>
	    <% if @item.bids.present? %>
	      <strong>Highest Bid: </strong> <%= number_to_currency(top_bid(@item).bid_amount, :unit => "$") %>
	    <% else %>
	      <strong>Starting Bid: </strong> <%= number_to_currency(@item.starting_bid, :unit => "$") %>
	    <% end %>
	  </p>
	  <p>
	    <strong>Minimum Increase: </strong> <%= number_to_currency(@item.min_increase, :unit => "$") %>
	  </p>
	  <p>
	    <% if !@item.item_description.nil? && !@item.item_description.empty? %><strong>Description: </strong> <%= @item.item_description %><% end %>
	  </p>
	</p>
  </div>
</div>
<br>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
  	<div class="btn-group btn-group-md btn-group-justified">
  	  <% if logged_in? && (!top_bid(@item).nil? && top_bid(@item).user_id!=current_user.id) || (logged_in? && top_bid(@item).nil?) %>
	  	<%= link_to new_item_bid_path(@item), class: 'btn btn-success' do %>
	  	  <span class="glyphicon glyphicon-usd"></span> Place Bid
	  	<% end %>
	  <% end %>
  	  <% if admin? %>
  	  	<%= link_to 'Edit Item', edit_item_path, class: "btn btn-primary", title: 'Edit details' %>
  	  	<%= link_to 'Back', admin_path, class: "btn btn-primary" %>
  	  <% else %>
  	    <%= link_to 'Back', auction_items_path(@item.auction_id), class: "btn btn-primary" %>
  	  <% end %>
  	</div>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
	<h3>Bid History</h3>
	<% if @bids.count > 0 %>
	  <table class="table table-striped">
	  	<thead>
	  	  <tr>
		  	<th>Name</th>
		  	<th>Amount</th>
		  </tr>
	  	</thead>
	  	<tbody>
	  	  <% @bids.order('bid_amount').reverse.each do |bid| %>
	  	  	<tr class="<%= bid==top_bid(@item) ? 'success' : '' %>">
	  	  	  <td>
	  	  	  	<% if User.find(bid.user_id) == current_user %>
	  	  	  		You
	  	  	  	<% else %>
	  	  	  		<% if User.find(bid.user_id).name_visible || admin? %>
	  	  	  			<%= User.find(bid.user_id).first_name %>
	  	  	  		<% else %>Anonymous<% end %></td>
	  	  	  	<% end %>
	  	  	  <td><%= number_to_currency(bid.bid_amount, :unit => '$') %></td>
	  	  	</tr>
	  	  <% end %>
	  	</tbody>
	  </table>
	<% else %>
	<p>No bids have been placed. Be the first!</p>
	<% end %>
  </div>
</div>